FROM node:20 AS build

WORKDIR /app
 
COPY package*.json ./
RUN npm install
 
COPY . .
 
RUN npm run build
 
FROM node:20 AS preview
 
WORKDIR /app
 
COPY package*.json ./
RUN npm install --production
 
COPY --from=build /app/dist /app/dist
 
EXPOSE 4173
 
CMD ["npm", "run", "dev"]